services:
  traefik:
    image: traefik
    ports:
      - 8000:80
    networks:
      - "web"
    command:
     - "--providers.docker=true"
     - "--entrypoints.web.address=:80"
     - "--providers.docker.endpoint=http://host.docker.internal:2375"
     - "--log.level=DEBUG"
     - "--api=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.rule=Host(`traefik.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      #- "traefik.http.routers.traefik.middlewares=auth" # Habilitar autenticação básica
      #- "traefik.http.middlewares.auth.basicauth.users=usuario:senhaBcrypt" # Senha bcrypr
  frontend:
    image: nginxdemos/hello
    ports:
      - 80
    networks:
      - "web"
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.routers.frontend.rule=Host(`frontend.local`)"
  backend:
    image: nginxdemos/hello
    ports:
      - 80
    networks:
      - "web"
    deploy:
      replicas: 2
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.routers.backend.rule=Host(`backend.local`)"

networks:
  web:
    external: true
#docker network create web